### ISSUE TITLE
About SwD_v2 efficiency

### ISSUE THREAD

**Issue by Tonshy** [gkaposto/Swarm-Decomposition#1]
I tried to use it to process real EEG signals and tried to change the parameters(thresh and depth)， but I still found it is slower than the original one. What are the possible causes?

**Comment by gkaposto** [comment]
The main difference of v2 compared to v1 is that a preprocessing stage takes place in order to calculate the proper resampling of the input signal. The core idea is the identical. Moreover, it has been added a zero-phase logic (forward and time reversal filtering). So it is anticipated to be slower than the original due to the added logic. 
In case you make an ad-hoc resampling and you do not care about small added delay, the original version maybe the better.

**Comment by Tonshy** [comment]
Thanks for your apply!
